{
  imports = [
    ./besserestrichliste.nix
    ./bird-lg.nix
    ./common.nix
    ./essen-jetzt.nix
    ./event.nix
    ./externally-managed.nix
    ./gulasch.nix
    ./homeassistant.nix
    ./knot.nix
    ./machines.nix
    ./mail.nix
    ./matrix-lite.nix
    ./matrix.nix
    ./monitoring.nix
    ./n50camp.nix
    ./photos.nix
    ./root.nix
    ./rudelshopping.nix
    ./voidspace.nix
    ./dn42-peers.nix
  ];
}
