{
 "title": "DN42",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(bird_protocol_up,instance)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(bird_protocol_up{proto=\"BGP\", instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DN42 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface!=\"cli\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{interface}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes_total{interface!=\"cli\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{interface}} "
    }
   ]
  },
  {
   "title": "BGP Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bird_protocol_up{proto=\"BGP\",instance=~\"$instance\",name=~\"$protocol\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "BGP Routes",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "bird_protocol_prefix_import_count{proto=\"BGP\",instance=~\"$instance\",name=~\"$protocol\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bird_protocol_prefix_export_count{proto=\"BGP\",instance=~\"$instance\",name=~\"$protocol\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\",instance=~\"$instance\",name=~\"$protocol\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "wireguard_sent_bytes_total{interface!=\"cli\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_received_bytes_total{interface!=\"cli\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - wireguard_latest_handshake_seconds{interface!=\"cli\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}